version: '2'

services:
    php:
        build: ./php
        restart: always
        volumes:
            - ../app/symphony:/var/www/app/symphony
        container_name: 'php'
    nginx:
        image: nginx:latest
        restart: always
        ports:
            -   "5555:80"
        volumes:
            -   ../app/symphony:/var/www/app/symphony
            -   ../nginx/main.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            -   php
    mysql:
        image: mysql:8
        restart: always
        ports:
            -   "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        container_name: 'mysql'
    adminer:
        image: adminer
        restart: always
        ports:
            -   "8080:8080"